"use strict";
var Injector_1 = require("./Injector");
exports.Injector = Injector_1.Injector;
var InjectableMiddleware_1 = require("./InjectableMiddleware");
exports.Injectable = InjectableMiddleware_1.Injectable;
var IntegerPromisifyMiddleware_1 = require("./IntegerPromisifyMiddleware");
exports.IntegerPromisifer = IntegerPromisifyMiddleware_1.IntegerPromisifer;
var WorkerMiddleware_1 = require("./WorkerMiddleware");
exports.WorkerMiddleware = WorkerMiddleware_1.WorkerMiddleware;
var PromisifyMiddleware_1 = require("./PromisifyMiddleware");
exports.Promisify = PromisifyMiddleware_1.Promisify;
var ControllerView_1 = require("./ControllerView");
exports.ControllerView = ControllerView_1.ControllerView;
var Store_1 = require("./Store");
exports.Store = Store_1.Store;
var LocalStoragePersistentStrategy_1 = require("./LocalStoragePersistentStrategy");
exports.localStorageStrategy = LocalStoragePersistentStrategy_1.localStorageStrategy;
(function (StrikeJS) {
    StrikeJS.localStorageStrategy = LocalStoragePersistentStrategy_1.localStorageStrategy;
    StrikeJS.Store = Store_1.Store;
    StrikeJS.ControllerView = ControllerView_1.ControllerView;
    StrikeJS.Promisify = PromisifyMiddleware_1.Promisify;
    StrikeJS.WorkerMiddleware = WorkerMiddleware_1.WorkerMiddleware;
    StrikeJS.IntegerPromisifier = IntegerPromisifyMiddleware_1.IntegerPromisifer;
    StrikeJS.Injectable = InjectableMiddleware_1.Injectable;
    StrikeJS.Injector = Injector_1.Injector;
}(window.StrikeJS = window.StrikeJS || {}));
